export const pieces = {
  black: {
    R: {
      id: 'R',
      name: 'Rook',
      url: './assets/chess-set/black/rook.png',
      type: 'black',
    },
    H: {
      id: 'H',
      name: 'Knight',
      url: './assets/chess-set/black/knight.png',
      type: 'black',
    },
    B: {
      id: 'B',
      name: 'Bishop',
      url: './assets/chess-set/black/bishop.png',
      type: 'black',
    },
    Q: {
      id: 'Q',
      name: 'Queen',
      url: './assets/chess-set/black/queen.png',
      type: 'black',
    },
    K: {
      id: 'K',
      name: 'King',
      url: './assets/chess-set/black/king.png',
      type: 'black',
    },
    P: {
      id: 'P',
      name: 'Pawn',
      url: './assets/chess-set/black/pawn.png',
      type: 'black',
    },
  },
  white: {
    R: {
      id: 'R',
      name: 'Rook',
      url: './assets/chess-set/white/rook.png',
      type: 'white',
    },
    H: {
      id: 'H',
      name: 'Knight',
      url: './assets/chess-set/white/knight.png',
      type: 'white',
    },
    B: {
      id: 'B',
      name: 'Bishop',
      url: './assets/chess-set/white/bishop.png',
      type: 'white',
    },
    Q: {
      id: 'Q',
      name: 'Queen',
      url: './assets/chess-set/white/queen.png',
      type: 'white',
    },
    K: {
      id: 'K',
      name: 'King',
      url: './assets/chess-set/white/king.png',
      type: 'white',
    },
    P: {
      id: 'P',
      name: 'Pawn',
      url: './assets/chess-set/white/pawn.png',
      type: 'white',
    },
  },
  E: {
    id: null,
    name: 'Empty',
  },
};

const { black, white, E } = pieces;

window.boardState = [
  'THIS VALUE DOESNT MATTER',
  black.R,
  black.H,
  black.B,
  black.Q,
  black.K,
  black.B,
  black.H,
  black.R,
  black.P,
  black.P,
  black.P,
  black.P,
  black.P,
  black.P,
  black.P,
  black.P,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  white.P,
  white.P,
  white.P,
  white.P,
  white.P,
  white.P,
  white.P,
  white.P,
  white.R,
  white.H,
  white.B,
  white.Q,
  white.K,
  white.B,
  white.H,
  white.R,
];
